buildings = [
  {
    '_id': '1',
    'name': 'San Francisco De Javier Building (SFJ)',
    'description': 'Multi-purpose academic building featuring classrooms and lecture halls.',
    'slots': '15',
    'totalSlots': '15',
    'image': '/assets/sfj.png',
  },  
  { 
    '_id': '2',
    'name': 'St. Michael Hall Building (SMH)',
    'description': 'Student residence hall providing dormitory accommodations.',
    'slots': '30',
    'totalSlots': '30',
    'image': '/assets/smh.jpg',
  },
  {
    '_id': '3',
    'name': 'Chapel of the Holy Guardian Angel',
    'description': 'Sacred space for prayer, worship, and religious observances.',
    'slots': '50',
    'totalSlots': '50',
    'image': '/assets/chapel.jpg',
  },
  { 
    '_id': '4',
    'name': 'Sister Josefina Nepomuceno Formation Center',
    'description': 'Center dedicated to educational development and spiritual formation programs.',
    'slots': '20',
    'totalSlots': '20',
    'image': '/assets/sjgn_fc.jpg',
  },
  {
    '_id': '5',
    'name': 'St. Joseph Hall Building (SJH)',
    'description': 'Residential facility for student housing and community living.',
    'slots': '25',
    'totalSlots': '25',
    'image': '/assets/sjh.jpg',
  },
  {
    '_id': '6',
    'name': 'Immaculate Heart Gymnasium',
    'description': 'Sports facility for athletics, fitness activities, and recreational programs.',
    'slots': '20',
    'totalSlots': '20',
    'image': '/assets/ihm_gym.jpg',
  },
    {
    '_id': '7',
    'name': 'Archbishop Pedro Santos Building (APS)',
    'description': 'Administrative and academic facility serving institutional functions.',
    'slots': '10',
    'totalSlots': '10',
    'image': '/assets/aps.jpg',
  },
    {
    '_id': '8',
    'name': 'Main Building',
    'description': 'Central administrative hub for the institution with primary offices.',
    'slots': '10',
    'totalSlots': '10',
    'image': '/assets/main.jpg',
  },
]