# Generated by Django 6.0.2 on 2026-03-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservation_is_completed_alter_building_maxslots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
