# Generated by Django 6.0.2 on 2026-03-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assignment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
